// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/Login": {
    params: {};
  };
  "/SignUp": {
    params: {};
  };
  "/Timetable": {
    params: {};
  };
  "/Social": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/Login" | "/SignUp" | "/Timetable" | "/Social";
  };
  "Pages/homePage/home.tsx": {
    id: "Pages/homePage/home";
    page: "/";
  };
  "Pages/login/login.tsx": {
    id: "Pages/login/login";
    page: "/Login";
  };
  "Pages/signUp/signUp.tsx": {
    id: "Pages/signUp/signUp";
    page: "/SignUp";
  };
  "Pages/timetable/timetable.tsx": {
    id: "Pages/timetable/timetable";
    page: "/Timetable";
  };
  "Pages/social/social.tsx": {
    id: "Pages/social/social";
    page: "/Social";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "Pages/homePage/home": typeof import("./app/Pages/homePage/home.tsx");
  "Pages/login/login": typeof import("./app/Pages/login/login.tsx");
  "Pages/signUp/signUp": typeof import("./app/Pages/signUp/signUp.tsx");
  "Pages/timetable/timetable": typeof import("./app/Pages/timetable/timetable.tsx");
  "Pages/social/social": typeof import("./app/Pages/social/social.tsx");
};