// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/Login": {
    params: {};
  };
  "/SignUp": {
    params: {};
  };
  "/Timetable": {
    params: {};
  };
  "/Social": {
    params: {};
  };
  "/Profile": {
    params: {};
  };
  "/Profile/edit": {
    params: {};
  };
  "/Chat/:conversationId": {
    params: {
      "conversationId": string;
    };
  };
  "/Inbox": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/Login" | "/SignUp" | "/Timetable" | "/Social" | "/Profile" | "/Profile/edit" | "/Chat/:conversationId" | "/Inbox";
  };
  "Pages/homePage/home.tsx": {
    id: "Pages/homePage/home";
    page: "/";
  };
  "Pages/auth/login.tsx": {
    id: "Pages/auth/login";
    page: "/Login";
  };
  "Pages/auth/signUp.tsx": {
    id: "Pages/auth/signUp";
    page: "/SignUp";
  };
  "Pages/timetable/timetable.tsx": {
    id: "Pages/timetable/timetable";
    page: "/Timetable";
  };
  "Pages/social/social.tsx": {
    id: "Pages/social/social";
    page: "/Social";
  };
  "Pages/userProfile/mainProfile.tsx": {
    id: "Pages/userProfile/mainProfile";
    page: "/Profile";
  };
  "Pages/userProfile/editProfile.tsx": {
    id: "Pages/userProfile/editProfile";
    page: "/Profile/edit";
  };
  "Pages/social/chat/chatRoom.tsx": {
    id: "Pages/social/chat/chatRoom";
    page: "/Chat/:conversationId";
  };
  "Pages/social/chat/inbox.tsx": {
    id: "Pages/social/chat/inbox";
    page: "/Inbox";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "Pages/homePage/home": typeof import("./app/Pages/homePage/home.tsx");
  "Pages/auth/login": typeof import("./app/Pages/auth/login.tsx");
  "Pages/auth/signUp": typeof import("./app/Pages/auth/signUp.tsx");
  "Pages/timetable/timetable": typeof import("./app/Pages/timetable/timetable.tsx");
  "Pages/social/social": typeof import("./app/Pages/social/social.tsx");
  "Pages/userProfile/mainProfile": typeof import("./app/Pages/userProfile/mainProfile.tsx");
  "Pages/userProfile/editProfile": typeof import("./app/Pages/userProfile/editProfile.tsx");
  "Pages/social/chat/chatRoom": typeof import("./app/Pages/social/chat/chatRoom.tsx");
  "Pages/social/chat/inbox": typeof import("./app/Pages/social/chat/inbox.tsx");
};