"""Add user_modules table

Revision ID: 67f8dbd033bc
Revises: 8d40c9310e4c
Create Date: 2026-05-30 13:01:33.352623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f8dbd033bc'
down_revision: Union[str, Sequence[str], None] = '8d40c9310e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_modules_id'), 'user_modules', ['id'], unique=False)
    op.create_index(op.f('ix_user_modules_module_code'), 'user_modules', ['module_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_modules_module_code'), table_name='user_modules')
    op.drop_index(op.f('ix_user_modules_id'), table_name='user_modules')
    op.drop_table('user_modules')
    # ### end Alembic commands ###
