"""add friends table

Revision ID: ad36d40daaa8
Revises: d6286ea1b6e2
Create Date: 2026-06-12 15:49:03.285632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad36d40daaa8'
down_revision: Union[str, Sequence[str], None] = 'd6286ea1b6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('friend_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'friend_profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
