"""added indexing to friendRequest

Revision ID: c89738e6dfde
Revises: f5d2cc634141
Create Date: 2026-06-13 19:48:41.313720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89738e6dfde'
down_revision: Union[str, Sequence[str], None] = 'f5d2cc634141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_friend_requests_receiver_id'), 'friend_requests', ['receiver_id'], unique=False)
    op.drop_constraint(op.f('friend_requests_sender_id_fkey'), 'friend_requests', type_='foreignkey')
    op.drop_column('friend_requests', 'sender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('friend_requests_sender_id_fkey'), 'friend_requests', 'user_profiles', ['sender_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_friend_requests_receiver_id'), table_name='friend_requests')
    # ### end Alembic commands ###
